### ISSUE TITLE
EngineStates do not allow you to specify System Priority.

### ISSUE THREAD

**Issue by IkonOne** [nadako/Ash-Haxe#25]
The system 'add' functions in EngineState do not allow the System priority to be specified.

https://github.com/nadako/Ash-Haxe/blob/master/src/ash/fsm/EngineStateMachine.hx

**Comment by T1mL3arn** [comment]
When you do ```state.addInstance()``` you get link to ```StateSystemMapping``` object, it has  ```withPriority()``` method to specify priority for the system.

So you can do
```Haxe
state.addInstance(new PhysicSystem()).withPriority(1)
     .addInstance(new CameraSystem()).withPriority(2)
     .addInstance(new PreUpdateSystem()).withPriority(0);
```

**Comment by IkonOne** [comment]
Ah yes.  Thank you.  I'll just close this and walk away like nothing happened...

**Comment by T1mL3arn** [comment]
Don't forget to close other related issues!
