### ISSUE TITLE
Tests failed with haxe 3.3.0

### ISSUE THREAD

**Issue by gogoprog** [nadako/Ash-Haxe#32]
Hello,

I just ran :

    haxe test.hxml

And it prints the following :

    /home/gogoprog/.haxelibs/hamcrest/2,0,1/org/hamcrest/collection/IsHashContaining.hx:36: characters 26-34 : Warning : Usage of this typedef is deprecated
    test/ash/core/SystemTest.hx:218: characters 33-45 : Unknown identifier : sameInstance
    test/ash/core/SystemTest.hx:224: characters 33-45 : Unknown identifier : sameInstance
    test/ash/core/SystemTest.hx:169: characters 49-61 : Unknown identifier : sameInstance
    test/ash/core/SystemTest.hx:196: characters 34-46 : Unknown identifier : sameInstance
    test/ash/core/AshAndFamilyIntegrationTest.hx:48: characters 37-49 : Unknown identifier : sameInstance
    ...

I don't know if it this linked to the latest version.
By the way using the framework seems to be fine, just the tests are failing.

**Comment by nadako** [comment]
I think those tests require older version of munit or hamcrest or something. I'll look into it and set specific versions in hxml.

**Comment by gogoprog** [comment]
I checked a bit and I think it would be better to update the test code to match the latest munit/hamcrest versions
